let questions = [
  "What is your favorite book and why?",
  "If you could travel to any place in the world, where would it be and why?",
  "What is your most memorable childhood memory?",
  "If you could have any superpower, what would it be and how would you use it?",
  "What is your favorite hobby and how did you get into it?",
  "If you could meet any historical figure, who would it be and what would you ask them?",
  "What is your favorite movie and what makes it special to you?",
  "Describe your perfect day. What would you do from morning to night?",
  "If you could only eat one type of food for the rest of your life, what would it be?",
  "What is the most challenging thing you’ve ever done?",
  "If you won a million dollars, what would you do with the money?",
  "What is your favorite season and why?",
  "Do you prefer dogs or cats? Why?",
  "What is a skill you’ve always wanted to learn and why?",
  "If you could live in any time period, past or future, when would it be and why?",
  "What is your favorite way to relax after a long day?",
  "Describe a dream you’ve had recently.",
  "What is your favorite holiday and how do you celebrate it?",
  "What is one thing you can’t live without and why?",
  "If you could switch lives with anyone for a day, who would it be and what would you do?",
  "What is the meaning of life to you?",
  "Do you believe in fate or free will? Why?",
  "What do you think happens after we die?",
  "What is the most important lesson you’ve learned in life so far?",
  "How do you define happiness, and do you think you’ve achieved it?",
  "What is more important: to be loved or to love?",
  "What is the role of art in society?",
  "Who is your favorite character from the Marvel Cinematic Universe and why?",
  "What is your favorite TV show of all time?",
  "If you could have dinner with any celebrity, who would it be and what would you ask them?",
  "Which city do you think is the best to visit in the world and why?",
  "Which is the nicest celebrity in your opinion?",
  "What is your favorite scene from a TV show?",
  "If you could visit any fictional place from a movie or TV show, where would you go?",
  "Who do you think is the best musician of the 21st century?",
  "What is your favorite Disney movie and what makes it special to you?",
];

export { questions };
